### ISSUE TITLE
代码运行错误提示

### ISSUE THREAD

**Issue by wangjiwang** [forskamse/RaspberryPi-Bluetooth-Punch-System#1]
你好，依赖环境等都安装好了。运行时出现以下错误，是怎么回事呢？
Traceback (most recent call last):
  File "/home/pi/RaspberryPi-Bluetooth-Punch-System/bluetooth-punch.py", line 19, in <module>
    last_punchFlag = df.iat[-1,0]
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 1665, in __getitem__
    return self.obj.get_value(*key, takeable=self._takeable)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 1896, in get_value
    return _maybe_box_datetimelike(series._values[index])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by forskamse** [comment]
此版代码已不再使用。已更新新版本出勤信息收集系统，如仍有需要，可下载使用。
